### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class "Swoole\Database\PDOPool" not found 

### ISSUE THREAD

**Issue by siamakdals** [openswoole/openswoole#14]
After updating to latest version i get this error :
PHP Fatal error:  Uncaught Error: Class "Swoole\Database\PDOPool" not found in

**Comment by doubaokun** [comment]
Example of using PDOPool in v22 is added: https://github.com/openswoole/openswoole/blob/master/example/src/Coroutine/MySQLClientPool.php
