### ISSUE TITLE
`Call to undefined method PDO::close()` when closing connection pool

### ISSUE THREAD

**Issue by Lustmored** [openswoole/openswoole#18]
Any attempt to call `$pool->close()` on a `ClientPool` with `PDO` connections ends with:

```
Error: Uncaught Error: Call to undefined method PDO::close() in ./vendor/openswoole/core/src/Coroutine/Client/PDOClient.php:46  
  Stack trace:                                                                                                                                                   
  #0 ./vendor/openswoole/core/src/Coroutine/Pool/ClientPool.php(89): OpenSwoole\Core\Coroutine\Client\PDOClient->__call()         
  #1 ./src/WebSocket/PoolRunner/AbstractRunner.php(19): OpenSwoole\Core\Coroutine\Pool\ClientPool->close() 
```

Client pool attempts to close remaining collections by calling non-existent `close` method on underlying objects.

**Comment by curruwilla** [comment]
I have the same problem.

**Comment by Lustmored** [comment]
@jsanahuja Sure, I will test it on Monday on one of my main projects :+1:

**Comment by curruwilla** [comment]
> As discussed in discord, the problem is at: https://github.com/openswoole/openswoole/blob/master/core/src/Coroutine/Pool/ClientPool.php#LL89C17-L89C34 Where ClientPool calls which "redirects" the call from to object here: https://github.com/openswoole/openswoole/blob/master/core/src/Coroutine/Client/PDOClient.php#L46 While has no method.`$client->close()``PDOClient``PDO``PDO``close`
> 
> The best approach in my opinion would be to define the close method in PDOClient and simply unset $__object in it.

this change you made in the other project tolerated the problem 🤔
https://github.com/openswoole/core/pull/4

**Comment by jsanahuja** [comment]
> > As discussed in discord, the problem is at: https://github.com/openswoole/openswoole/blob/master/core/src/Coroutine/Pool/ClientPool.php#LL89C17-L89C34 Where ClientPool calls which "redirects" the call from to object here: https://github.com/openswoole/openswoole/blob/master/core/src/Coroutine/Client/PDOClient.php#L46 While has no method.`` $client->close()``PDOClient``PDO``PDO``close ``
> > The best approach in my opinion would be to define the close method in PDOClient and simply unset $__object in it.
> 
> this change that I made in the other project, solved the problem 🤔 [openswoole/core#4](https://github.com/openswoole/core/pull/4)

Your change would work with `ClientPool` because `PDOClient` exits the `Channel` and is therefore destroyed destroying `PDO` as well. But the use of `PDOClient` is not limited to `ClientPool` and without it, the `close` method is useless: it does not close the connection. 

Also, as far as I know, [openswoole/core](https://github.com/openswoole/core/) is a read-only repository and all the changes have to be done here first.

**Comment by dhobi** [comment]
I have no idea where (which project) this change needs to be but I agree with @jsanahuja that the close() method should not just do nothing but trying to unset / null the active connection object ($this->__object)

I completely overlooked in core pr 3 that the PDOClient is just another wrapper. I wrongly assumed it has an "extends" relationship, hence the proposed do nothing approach in the close() method.

**Comment by jsanahuja** [comment]
> I have no idea where (which project) this change needs to be but I agree with @jsanahuja that the close() method should not just do nothing but trying to unset / null the active connection object ($this->__object)
> 
> I completely overlooked in core pr 3 that the PDOClient is just another wrapper. I wrongly assumed it has an "extends" relationship, hence the proposed do nothing approach in the close() method.

I added a comment on my PR https://github.com/openswoole/openswoole/pull/42#issuecomment-1566876085 about if we should control if the connection was closed in other methods. What do you think? Should other methods be aware of closed connections?

**Comment by dhobi** [comment]
Personally, I like this addition! I would even throw the exception everywhere the object in question is accessed. "Fail early" or "as soon as possible". 
Reason I mention this is that I've seen the code you proposed in isInTransaction. The exception would currently not be thrown there.

**Comment by jsanahuja** [comment]
> Personally, I like this addition! I would even throw the exception everywhere the object in question is accessed. "Fail early" or "as soon as possible". Reason I mention this is that I've seen the code you proposed in isInTransaction. The exception would currently not be thrown there.

I didn't mean to throw an exception unless the use of `__object` was really necessary. For `isInTransaction`, I thought we could simply return false. There's no need for the `__object` to indicate that we're not in a transaction if we're not even connected.

But I agree that the earlier we fail, the better. Also, a call to `isInTransaction` after `close` makes no sense, and without throwing the exception, the developer wouldn't realize they're doing something wrong.

I will implement it soon, and let's wait until Bruce finds time to review it.

Thanks @dhobi !
