### ISSUE TITLE
Missing Swoole\ConnectionPool in ide helper

### ISSUE THREAD

**Issue by mairo744** [openswoole/openswoole#24]
Hi,

it looks like connection pool (`Swoole\ConnectionPool`) is missing in version 22.0.0. 
I can find connection pool implementation in openswoole - https://github.com/openswoole/library/blob/master/src/core/ConnectionPool.php but can not find in openswoole ide helper - https://github.com/openswoole/ide-helper.

Also in changelog does not seem to be deprecated or removed - https://openswoole.com/article/v22-0-0-released .

Is there any replacement or why is missing in ide helper?

**Comment by jsanahuja** [comment]
I believe the replacement is `OpenSwoole\Core\Coroutine\Pool\ClientPool`

**Comment by doubaokun** [comment]
Example of using PDOPool in v22 is added: https://github.com/openswoole/openswoole/blob/master/example/src/Coroutine/MySQLClientPool.php
